#!/usr/bin/env python3
"""Translation dictionary for one language of the Layer 2 modules.

  dict.py template <lang>   -> writes work/<lang>.todo.json: [{"en": ..., "tr": ""}, ...]
                                (keeps existing translations from src/lib/i18n/<lang>.ts)
  dict.py build <lang>      -> reads work/<lang>.todo.json, validates, writes
                                PROJECT/src/lib/i18n/<lang>.ts, then runs the project check

Keys are the English source strings (`node scripts/i18n-check.mjs --keys`). Placeholders
{0}, {1}, ... must appear in the translation exactly as in the English text.
"""
import sys, os, json, re, subprocess
sys.path.insert(0, os.path.dirname(__file__)); from _paths import PROJECT
WORK = os.path.join(os.path.dirname(__file__), 'work'); os.makedirs(WORK, exist_ok=True)
cmd, lang = sys.argv[1], sys.argv[2]
todo = os.path.join(WORK, f'{lang}.todo.json')
dst = os.path.join(PROJECT, f'src/lib/i18n/{lang}.ts')
def keys():
    out = os.path.join(WORK, '_keys.json')
    subprocess.run(['node', 'scripts/i18n-check.mjs', '--keys', out], cwd=PROJECT, check=True, capture_output=True)
    return json.load(open(out, encoding='utf-8'))
def existing():
    if not os.path.exists(dst): return {}
    t = open(dst, encoding='utf-8').read()
    return json.loads(t[t.index('{'):t.rindex('}') + 1])
ph = lambda s: sorted(re.findall(r'\{\d+\}', s))
if cmd == 'template':
    old = existing()
    rows = [{'en': k, 'tr': old.get(k, '')} for k in keys()]
    json.dump(rows, open(todo, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    print(f'{todo}: {len(rows)} strings, {sum(1 for r in rows if r["tr"])} already translated')
elif cmd == 'build':
    rows = json.load(open(todo, encoding='utf-8'))
    k = keys(); ks = set(k)
    empty = [r['en'] for r in rows if not r['tr'].strip()]
    stale = [r['en'] for r in rows if r['en'] not in ks]
    missing = [x for x in k if x not in {r['en'] for r in rows}]
    badph = [r['en'] for r in rows if r['tr'] and ph(r['en']) != ph(r['tr'])]
    for label, lst in (('EMPTY', empty), ('NOT A CURRENT KEY', stale), ('MISSING ROW', missing), ('PLACEHOLDER MISMATCH', badph)):
        for x in lst[:20]: print(label, json.dumps(x, ensure_ascii=False)[:120])
    if empty or missing or badph:
        sys.exit(f'not built: {len(empty)} empty, {len(missing)} missing, {len(badph)} placeholder mismatches')
    d = {r['en']: r['tr'] for r in rows if r['en'] in ks}
    body = json.dumps(d, ensure_ascii=False, indent=2)
    open(dst, 'w', encoding='utf-8').write(
        f"// {lang.upper()} dictionary for the Layer 2 modules, keyed by the English source text.\n"
        "// Generated by i18n-tools/layer2/dict.py build from work/<lang>.todo.json.\n"
        f"// Coverage check: node scripts/i18n-check.mjs\nconst {lang}: Record<string, string> = {body};\n\nexport default {lang};\n")
    print(f'wrote {dst} ({len(d)} strings)')
    subprocess.run(['node', 'scripts/i18n-check.mjs'], cwd=PROJECT)
