// Generated by build.mjs from data/partner-checklists.json. Do not edit by hand.
export default {
 "21bitcoin": {
  "name": "21bitcoin",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://21bitcoin.app/en",
   "https://21bitcoin.app/en/blog/this-is-how-opening-an-account-with-21bitcoin-works"
  ],
  "open_questions": [
   "Official domain is 21bitcoin.app (21bitcoin.com is unrelated).",
   "KYC details come from 21bitcoin's own blog article, not a help-centre page."
  ],
  "steps": {
   "en": [
    {
     "title": "Download the app and register",
     "text": "Download the 21bitcoin app and register with your email address. The service is available to residents of the EEA, Switzerland and the UK."
    },
    {
     "title": "Verify your identity",
     "text": "Have a valid ID card or passport ready and record a short selfie video in the app. The check is fully digital and usually takes a few minutes."
    },
    {
     "title": "Deposit euros by SEPA",
     "text": "After verification, send euros by SEPA transfer to your personal virtual IBAN. The transfer must come from a bank account in your own name."
    },
    {
     "title": "Buy Bitcoin",
     "text": "Once the deposit arrives, you can buy Bitcoin in the app. 21bitcoin lists purchases starting from €10."
    },
    {
     "title": "Set up a plan or own wallet",
     "text": "Optionally set up a recurring Bitcoin savings plan, or send your Bitcoin to your own wallet. The app can also transfer automatically to a hardware wallet."
    }
   ]
  }
 },
 "bybit-eu": {
  "name": "ByBit EU",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://www.bybit.eu/en-EU/learn/essential-guides/create-a-bybit-account",
   "https://www.bybit.eu/en-EU/help-center/article/How-to-Complete-Individual-KYC-Verification",
   "https://www.bybit.eu/en-EU/learn/bybit-guide/eur-deposit-withdrawal"
  ],
  "open_questions": [
   "Exact in-app steps for a first Bitcoin purchase not found on an official page.",
   "Bybit EU's crypto-withdrawal help article says it 'is currently not supported on this site'; no withdrawal step included.",
   "Only SEPA funding included."
  ],
  "steps": {
   "en": [
    {
     "title": "Download the app and sign up",
     "text": "Download the official Bybit EU app and select your EEA country of residence. Enter an email or mobile number, confirm the verification code and set a password."
    },
    {
     "title": "Complete Standard Verification",
     "text": "This is mandatory for EEA users. Choose Quick, Bank or Video Verification, photograph the front and back of a valid ID, and complete a selfie liveness check."
    },
    {
     "title": "Answer the profile survey",
     "text": "After verification, answer a seven-question profile survey and enter your residential address. In some cases you may be asked for a recent proof of address."
    },
    {
     "title": "Deposit EUR by SEPA",
     "text": "In the app go to More, Deposit, Fiat, select EUR and SEPA Transfer. Send from a bank account in your name and include the reference code."
    },
    {
     "title": "Buy Bitcoin with Spot Trading",
     "text": "Once you are verified, Bybit EU lists Spot Trading among the products available to you. You can use it to buy Bitcoin with your EUR balance."
    }
   ]
  }
 },
 "kraken": {
  "name": "Kraken",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://support.kraken.com/hc/en-us/articles/360059110151-Creating-and-verifying-your-account-on-the-Kraken-app",
   "https://support.kraken.com/articles/360021973671-how-to-get-verified-on-kraken",
   "https://support.kraken.com/articles/360000381846-cash-deposit-options-fees-minimums-and-processing-times-",
   "https://support.kraken.com/articles/360058727972-buying-selling-and-converting-cryptocurrency-with-the-kraken-app",
   "https://support.kraken.com/articles/360000672763-how-to-withdraw-cryptocurrencies-from-your-kraken-account"
  ],
  "open_questions": [
   "Verification screens may differ by location; EU face-photo vs proof-of-address not confirmed.",
   "Fees/minimums per deposit method left out."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your account",
     "text": "Open the Kraken app, tap Create account, enter your email, a password and your country of residence. Then enter the activation code sent by email."
    },
    {
     "title": "Verify your identity",
     "text": "Provide your phone number, name, date of birth, address and occupation. Upload an ID (national ID, passport or driving licence) and a proof of address, such as a utility bill."
    },
    {
     "title": "Deposit EUR",
     "text": "Kraken lists SEPA and SEPA Instant transfers, PayPal and debit cards for EUR deposits, plus iDEAL in the Netherlands. Include the account reference if the instructions show one."
    },
    {
     "title": "Buy Bitcoin",
     "text": "Tap + and then Buy, select Bitcoin, enter the amount and choose a payment method. Review the purchase and tap Confirm."
    },
    {
     "title": "Withdraw to your own wallet",
     "text": "In Portfolio, tap Withdraw, select Bitcoin and the network your wallet uses. Paste or scan your address, check the details, confirm, and enter your funding 2FA code if asked."
    }
   ]
  }
 },
 "crypto-com": {
  "name": "Crypto.com",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://help.crypto.com/en/articles/6185958-how-to-sign-up-for-the-crypto-com-app",
   "https://help.crypto.com/en/articles/9794701-set-up-eur-account",
   "https://help.crypto.com/en/articles/5440400-crypto-com-app-user-guide",
   "https://help.crypto.com/en/articles/2500695-crypto-withdrawals-general-information"
  ],
  "open_questions": [
   "Accepted ID types for EU users not confirmed on an opened page.",
   "Legal entity serving EEA customers and its MiCA licence not checked."
  ],
  "steps": {
   "en": [
    {
     "title": "Download the app and create account",
     "text": "Download the Crypto.com App and tap Create New Account. Confirm your email through the link sent to you, then verify your phone number with a 6-digit SMS code."
    },
    {
     "title": "Verify your identity",
     "text": "Enter your full legal name, select your ID's issuing country and type, and take a selfie. Requirements may vary by country."
    },
    {
     "title": "Open a EUR account and deposit",
     "text": "EEA residents can open a EUR account and deposit by SEPA using personal bank details. You may be asked for proof of address and for information about income and occupation."
    },
    {
     "title": "Buy Bitcoin",
     "text": "On the home screen tap Buy and select Bitcoin. Choose a purchase method, such as your cash balance or a card, enter the amount and confirm. Recurring Buy is also available."
    },
    {
     "title": "Withdraw to your own wallet",
     "text": "Go to Accounts, Token Wallet, Transfer, Withdraw, External Wallet. Add your wallet address first; if the feature is enabled, a new address is locked for 24 hours."
    }
   ]
  }
 },
 "invity": {
  "name": "Invity",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://invity.io",
   "https://invity.io/app-overview",
   "https://www.invity.io/blog/buying-your-first-bitcoin-with-invity-2"
  ],
  "open_questions": [
   "IMPORTANT: Invity is no longer a comparison platform; it is a Bitcoin-only accumulation app (Invity Finance s.r.o., Prague, CASP under MiCA, BitGo custody). Virtuse's card wording should be checked.",
   "Proof of address requirement not confirmed.",
   "Payment methods per country not verified.",
   "Turbo Buy left out (leverage-like, needs compliance review)."
  ],
  "steps": {
   "en": [
    {
     "title": "Download the app and sign up",
     "text": "Download the Invity app from the App Store or Google Play. Sign up with a Google account or an email and password. Invity serves residents of the EEA."
    },
    {
     "title": "Verify your identity",
     "text": "Photograph an official ID issued in the EEA or Switzerland, then take a selfie. In the Czech Republic you can verify with Bank iD instead."
    },
    {
     "title": "Fund your account and buy",
     "text": "Choose an amount and a payment method; Invity lists SEPA transfers and card payments. The fee is shown before you confirm each purchase."
    },
    {
     "title": "Optionally set up Auto Buy",
     "text": "Auto Buy purchases Bitcoin automatically at regular intervals, with an amount and schedule you choose."
    },
    {
     "title": "Keep or withdraw your Bitcoin",
     "text": "Bitcoin is held by Invity's custodian, BitGo, unless you withdraw it. You can withdraw to your own wallet at any time, or set Auto Send to transfer at a chosen balance."
    }
   ]
  }
 },
 "trezor": {
  "name": "Trezor",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://trezor.io/start",
   "https://trezor.io/support/a/is-my-device-safe-to-use",
   "https://trezor.io/guides/backups-recovery/general-standards/how-to-use-a-wallet-backup",
   "https://trezor.io/guides/trezor-suite/getting-to-know-trezor-suite"
  ],
  "open_questions": [
   "Model-specific seal location and authenticity check steps differ per device (Safe 3/5/7, Model T); per-model guides not opened.",
   "Exact Suite onboarding screens were not opened on a dedicated official page; trezor.io/start only says 'follow the steps' (about 15 minutes)."
  ],
  "steps": {
   "en": [
    {
     "title": "Buy from Trezor or an authorized reseller",
     "text": "Order from the official Trezor Shop, the Trezor Amazon storefront or an authorized reseller. Trezor advises never buying from an unauthorized third party."
    },
    {
     "title": "Check the packaging and holographic seal",
     "text": "Check that the package is intact with no signs of tampering and that your model's holographic seal is in place. Trezor devices ship without firmware installed."
    },
    {
     "title": "Install Trezor Suite and set up",
     "text": "Download Trezor Suite from trezor.io/start, connect the device and follow the on-screen setup. Suite only accepts the device if its firmware is signed by SatoshiLabs."
    },
    {
     "title": "Write down your wallet backup",
     "text": "Write the words correctly spelled and in order. Never share your wallet backup or keep digital copies (screenshots, photos, cloud). Trezor will never ask for it."
    },
    {
     "title": "Receive bitcoin in Trezor Suite",
     "text": "Open the Receive tab to generate an address. Before sharing it, confirm it matches the address shown on your Trezor device."
    }
   ]
  }
 },
 "ledger": {
  "name": "Ledger",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://www.ledger.com/academy/topics/ledgersolutions/best-practices-to-securely-buy-ledger-signer",
   "https://support.ledger.com/article/360018784134-zd",
   "https://support.ledger.com/article/4404389453841-zd"
  ],
  "open_questions": [
   "Recovery phrase length depends on model; 24 words verified only on the Nano X setup page.",
   "Box contents list seen only in a search snippet.",
   "Ledger's receive page also advises sending a small amount first; left out to keep the step short."
  ],
  "steps": {
   "en": [
    {
     "title": "Buy from Ledger or an authorized reseller",
     "text": "Order from the official Ledger shop, an official or authorized-reseller Amazon storefront, or an authorized reseller listed on ledger.com."
    },
    {
     "title": "Check the box before use",
     "text": "Do not use the device if the packaging appears opened or altered, or if a PIN or recovery phrase is already provided. Contact Ledger Support instead."
    },
    {
     "title": "Install Ledger Wallet and set up",
     "text": "Download Ledger Wallet (formerly Ledger Live) from official sources only. Choose Set up as new device and pick a PIN. The app runs a Genuine Check."
    },
    {
     "title": "Write down your Secret Recovery Phrase",
     "text": "Write down the 24-word Secret Recovery Phrase generated by the device. Never enter it into an application. Ledger will never ask for it."
    },
    {
     "title": "Add Bitcoin and receive",
     "text": "Install the Bitcoin app on the device and add a Bitcoin account. Select Receive, then verify the address on the device matches the one in Ledger Wallet."
    }
   ]
  }
 },
 "blockstream": {
  "name": "Blockstream",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://blockstream.com/jade/",
   "https://help.blockstream.com/hc/en-us/articles/19629901272345-Set-up-Jade",
   "https://help.blockstream.com/blockstream-jade/set-up-transact-recover-your-wallet/receive-bitcoin-using-jade"
  ],
  "open_questions": [
   "Official pages now name the companion app 'Blockstream app', not 'Blockstream Green'; Virtuse copy may need updating.",
   "No official page opened describes packaging/tamper checks on arrival.",
   "Blockstream does not state on the opened pages that it will never ask for the recovery phrase."
  ],
  "steps": {
   "en": [
    {
     "title": "Buy from the Blockstream store or reseller",
     "text": "Order Jade from store.blockstream.com or through Blockstream's reseller program."
    },
    {
     "title": "Power on and create a wallet",
     "text": "Turn on Jade by plugging it in or holding the power button. Select Begin Setup, then Create New Wallet to generate a new recovery phrase."
    },
    {
     "title": "Write down and verify the phrase",
     "text": "Write the recovery phrase down offline. Do not photograph it or store it digitally. Confirm the backup by selecting the correct words on Jade."
    },
    {
     "title": "Connect Jade to the Blockstream app",
     "text": "Install the Blockstream app and connect Jade via USB, Bluetooth or QR code to finish setup and set a PIN."
    },
    {
     "title": "Receive bitcoin",
     "text": "In the Blockstream app, open Transact, select Receive, then Verify on Device. Check that the address on Jade matches the app before sharing it."
    }
   ]
  }
 },
 "firefish": {
  "name": "Firefish",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://firefish.io/",
   "https://firefish.io/borrow",
   "https://docs.firefish.io/faq/general",
   "https://docs.firefish.io/firefish-protocol"
  ],
  "open_questions": [
   "Figures left out of steps. Official pages state 'rates from 5%', durations 3-24 months, loans 'from $800', 'up to half of your Bitcoin's value' (firefish.io/borrow, firefish.io). virtuse.com updated to 5% on 2026-10-07.",
   "Liquidation threshold (LTV 95%) only seen in a search snippet.",
   "KYC documents and supported countries/currencies for EU borrowers not verified.",
   "Top-up mechanics not opened."
  ],
  "steps": {
   "en": [
    {
     "title": "Sign up and verify your identity",
     "text": "Create an account at app.firefish.io. Firefish follows standard KYC/AML rules, so identity verification is required before borrowing."
    },
    {
     "title": "Submit a loan request",
     "text": "Choose a Standard Loan (you set terms including interest rate) or an Instant Loan (fixed rate). Requests are matched with an investor or listed for up to 30 days."
    },
    {
     "title": "Lock Bitcoin collateral in escrow",
     "text": "After accepting the loan agreement, set a Bitcoin return address and send collateral to a 3-of-3 multisig escrow on the Bitcoin blockchain."
    },
    {
     "title": "Receive funds and confirm",
     "text": "The investor sends the funds to your bank account. You confirm on the platform once they arrive, and the loan becomes active."
    },
    {
     "title": "Repay at the end of the term",
     "text": "Repay in full by bank transfer at term end and confirm on the platform. Collateral returns to your return address; it may be liquidated if it no longer secures the loan."
    }
   ]
  }
 },
 "koinly": {
  "name": "Koinly",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://support.koinly.io/en/articles/9489951-getting-started-with-koinly"
  ],
  "open_questions": [
   "How and where the user selects their tax country/currency was not described on the page read.",
   "No official Koinly guidance on API key permissions (read-only) was read; not included.",
   "Plan names/prices not checked; only the statement that a paid plan for the year is required to generate a report."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your Koinly account",
     "text": "Sign up on koinly.io. In Koinly, every exchange, wallet or service you use is called a \"Wallet\"."
    },
    {
     "title": "Add your exchanges and wallets",
     "text": "On the Wallets page, click Add Wallet, search for the exchange or wallet, and import via API or CSV. You can add public blockchain addresses directly."
    },
    {
     "title": "Wait for the calculations",
     "text": "Koinly processes the imported data: it matches transfers between your wallets, fetches market values and calculates gains. An \"Updating\" indicator shows while this runs."
    },
    {
     "title": "Review your transactions",
     "text": "Check that all wallets are added, compare end balances with your exchanges, and resolve \"Missing purchase history\" warnings before generating reports."
    },
    {
     "title": "Download your tax report",
     "text": "On the Tax Reports page, select the tax year, pick a report and click Download report. A paid plan for that year is required to generate reports."
    }
   ]
  }
 },
 "blockpit": {
  "name": "Blockpit",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://intercom.help/blockpit/en/articles/12136903-guide-first-steps-with-blockpit",
   "https://intercom.help/blockpit/en/articles/12137203-tax-report-tax-results-calculation-download-and-backup"
  ],
  "open_questions": [
   "Country/tax-jurisdiction selection step not described on the pages read.",
   "No official API key permission guidance (read-only) found on the pages read.",
   "Package prices not checked (pricing page exists at blockpit.io but was not opened)."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your Blockpit account",
     "text": "Sign up at blockpit.io. After signing up you land in the dashboard, where you add your integrations."
    },
    {
     "title": "Add your integrations",
     "text": "Add each exchange via API, each wallet or blockchain via its public address, or enter transactions manually. Repeat until all your integrations are imported."
    },
    {
     "title": "Sync and run the calculation",
     "text": "Use \"Sync All\" in the Integrations tab so all integrations are up to date, then start a calculation. Transactions are labelled and merged automatically."
    },
    {
     "title": "Review the tips",
     "text": "Check the tips Blockpit shows, such as mismatched balances, missing history or unlabelled transactions, and fix them before reporting."
    },
    {
     "title": "Generate and download the report",
     "text": "In Reports, select the tax year, click Calculate Report, then Download. Access requires purchasing the transaction package for that tax year."
    }
   ]
  }
 },
 "cointracking": {
  "name": "CoinTracking",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://cointracking.info/learn/import-exchange-data/",
   "https://cointracking.info/crypto-tax-calculator"
  ],
  "open_questions": [
   "How the user selects their country during setup was not described on the pages read (site says it supports 100+ countries).",
   "No dedicated official guidance on reviewing/reconciling transactions was read; review step folded into step 5.",
   "Plan prices/limits not checked beyond 'free plan available'."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your CoinTracking account",
     "text": "Sign up on cointracking.info. The site states a free plan is available and no credit card is required to start."
    },
    {
     "title": "Connect exchanges via API",
     "text": "In Import, choose your exchange and connect automatically. CoinTracking says to create a read-only API key with no trading or withdrawal permissions."
    },
    {
     "title": "Upload CSV or add wallet addresses",
     "text": "For exchanges without API, export a CSV of your full history and upload it. Wallets can be imported via public address; manual entry is also possible."
    },
    {
     "title": "Choose your accounting method",
     "text": "CoinTracking matches buys and sells and applies the accounting method you set in settings (FIFO, LIFO or HIFO) to calculate gains and losses."
    },
    {
     "title": "Generate your tax report",
     "text": "Once your data is imported and checked, generate the tax report covering capital gains, income, fees and losses."
    }
   ]
  }
 },
 "divly": {
  "name": "Divly",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://help.divly.com/en/articles/8177216-step-1-set-up-your-divly-account",
   "https://help.divly.com/en/articles/8238384-how-do-i-import-my-crypto-transactions-into-divly"
  ],
  "open_questions": [
   "Whether downloading the report requires a paid plan was not verified; prices not checked."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your Divly account",
     "text": "Register and select \"Individual - I'll manage my own taxes\". Then choose the country you pay taxes in, your local currency and language."
    },
    {
     "title": "Import your crypto transactions",
     "text": "On the Wallets page, search for each wallet or exchange and follow its instructions: automatic import (API/OAuth) or CSV/XLSX file upload."
    },
    {
     "title": "Use read-only API keys",
     "text": "Divly states you should only create read-only API keys, as it only needs access to transaction data. File imports need a new upload for new transactions."
    },
    {
     "title": "Review your transactions",
     "text": "In the Transactions tab, check your imported transactions and add, edit or delete them manually where needed."
    },
    {
     "title": "Download your tax report",
     "text": "In the Tax Report section, track your taxes and download the report to submit to your local tax authority."
    }
   ]
  }
 },
 "coinrule": {
  "name": "Coinrule",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://help.coinrule.com/en/articles/4996703-connect-an-exchange",
   "https://help.coinrule.com/en/articles/4799149-build-a-rule",
   "https://help.coinrule.com/en/articles/5195048-how-the-demo-exchange-works"
  ],
  "open_questions": [
   "Sign-up flow itself not read on an official help page.",
   "Plans/prices not checked; which features need a paid plan not verified."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your Coinrule account",
     "text": "Sign up on coinrule.com to access the dashboard and rule editor."
    },
    {
     "title": "Connect your exchange via API",
     "text": "Create an API key on your exchange and paste it into Coinrule. Coinrule states keys need no withdrawal rights; do not enable API transfer. Binance supports IP whitelisting."
    },
    {
     "title": "Build a rule",
     "text": "Click Create Rule. Choose the exchange, set the conditions that trigger the rule, then the buy or sell actions. Optional operators combine several blocks."
    },
    {
     "title": "Test on the Demo Exchange",
     "text": "Select Demo Exchange to run rules on simulated funds using real-time Binance market data and a simulated 0.1% fee, with no real assets at risk."
    },
    {
     "title": "Set limits and launch",
     "text": "Set the launch time and an execution limit per timeframe to avoid over-trading, then launch the rule. You can also save it as a draft."
    }
   ]
  }
 },
 "cryptohopper": {
  "name": "Cryptohopper",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://docs.cryptohopper.com/docs/fundamentals/new-bot-wizard",
   "https://docs.cryptohopper.com/docs/fundamentals",
   "https://docs.cryptohopper.com/docs/how-to-connect/binance"
  ],
  "open_questions": [
   "Security guidance taken from the Binance connection guide; exact permission names differ per exchange (e.g. Kraken) and were not checked.",
   "Subscription prices not checked."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your Cryptohopper account",
     "text": "Register on cryptohopper.com, then open My bots, click View all and start the Config Wizard."
    },
    {
     "title": "Start with simulated funds if preferred",
     "text": "In the wizard you can choose \"Simulated funds\" (paper trading), which needs no exchange connection, to practise before using real funds."
    },
    {
     "title": "Connect your exchange via API",
     "text": "Create an API key on your exchange with trade and read rights only. Do not enable withdrawal rights. Whitelist Cryptohopper's IP addresses, then paste the key."
    },
    {
     "title": "Configure your bot",
     "text": "Choose \"Follow signals\" and subscribe to a signaler, or \"Build your bot\" and pick a risk strategy."
    },
    {
     "title": "Review and start trading",
     "text": "Review the bot summary and click Start trading. Cryptohopper states every bot trading real funds needs an active subscription."
    }
   ]
  }
 },
 "revenuebot": {
  "name": "RevenueBot",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://desk.revenuebot.io/en/knowledgebase/article/what-is-an-api-key-what-is-it-for",
   "https://desk.revenuebot.io/en/knowledgebase/article/how-to-create-a-bot-on-the-revenuebot-platform"
  ],
  "open_questions": [
   "Knowledge base lists a 'Bot simulation mode (backtest)' category, but no details were read; test/paper mode left out.",
   "FASTAPI one-click key connection exists per search result but the article was not opened; left out.",
   "Sign-up flow and pricing not read on an official page."
  ],
  "steps": {
   "en": [
    {
     "title": "Create your RevenueBot account",
     "text": "Sign up on revenuebot.io to access the API Keys and Bots tabs."
    },
    {
     "title": "Create a trade-only API key",
     "text": "On your exchange, create an API key that can trade but cannot withdraw funds, as RevenueBot's knowledge base instructs."
    },
    {
     "title": "Add the key to RevenueBot",
     "text": "In the API Keys tab, click Add API key, name it, select the exchange and enter the public and secret parts. One key can serve several bots."
    },
    {
     "title": "Configure a new bot",
     "text": "In the Bots tab, click Create a new bot. Select exchange, API key, trading pair, algorithm, deposit amount, template and filters."
    },
    {
     "title": "Create and start the bot",
     "text": "Click to create the bot, review its settings, then click Start to begin trading."
    }
   ]
  }
 },
 "oneminers": {
  "name": "OneMiners",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://www.oneminers.com/",
   "https://www.oneminers.com/pages/how-to-buy",
   "https://www.oneminers.com/pages/asset-withdrawal-guide",
   "https://www.oneminers.com/pages/shipping-how-does-it-work"
  ],
  "open_questions": [
   "No written description of mining pool connection: payouts appear to go to a OneMiners wallet balance first.",
   "Shipping & Batch System page explains the process only in an embedded video.",
   "KYC/account verification requirements not found on the pages read.",
   "Homepage pricing/BNPL left out as marketing."
  ],
  "steps": {
   "en": [
    {
     "title": "Log in and choose a miner",
     "text": "Log in to your OneMiners account, open 'Products' in the dashboard, review a machine's details and add it to your cart."
    },
    {
     "title": "Check out with hosting preference",
     "text": "At checkout, select shipping or hosting, enter billing and shipping details, choose a payment option, review the order and place it."
    },
    {
     "title": "Wait for setup",
     "text": "After payment the order is processed and you get status updates. OneMiners states setup is typically completed within 72 hours, then the machine appears under 'Active miners'."
    },
    {
     "title": "Withdraw to your own wallet",
     "text": "In 'WalletBalance', click 'Withdraw', enter the amount and your Bitcoin address, preview the fees, confirm. OneMiners states withdrawals are processed within 24 hours."
    }
   ]
  }
 },
 "abundant-mines": {
  "name": "Abundant Mines",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://abundantmines.com/",
   "https://abundantmines.com/faq/",
   "https://abundantmines.com/book-a-call/"
  ],
  "open_questions": [
   "Facility location(s) and whether EU customers are served not confirmed.",
   "KYC requirements not addressed in the FAQ.",
   "FAQ minimum investment figures (approx. USD 6,200-12,000+) omitted."
  ],
  "steps": {
   "en": [
    {
     "title": "Book a consultation",
     "text": "Book a call through the Abundant Mines website to discuss your goals, timeline and criteria with their team."
    },
    {
     "title": "Acquire your miners",
     "text": "The team helps you select equipment. Per the FAQ, machines are already on site and ready to deploy; you own the miners."
    },
    {
     "title": "Agree hosting payment terms",
     "text": "Hosting is paid yearly upfront or month to month; month to month requires a two-month prepayment, per the FAQ."
    },
    {
     "title": "Onboarding and pool setup",
     "text": "The facility installs your miner and points it to the mining pool and wallet you choose. The FAQ states onboarding takes 1-3 weeks."
    },
    {
     "title": "Withdraw to your own custody",
     "text": "Mining is non-custodial: bitcoin goes to your chosen pool and you withdraw it to your own custody. Abundant Mines states it never takes custody."
    }
   ]
  }
 },
 "power-mining": {
  "name": "PowerMining",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://powermining.io/",
   "https://powermining.io/pages/frequently-asked-questions"
  ],
  "open_questions": [
   "Hosting service not found on pages read; shop.powermining.io not checked separately.",
   "FAQ states home miners are hobby devices and not to expect financial returns; consider keeping that wording.",
   "Warranty terms differ between homepage (90 days) and FAQ (2 years EU consumers); confirm."
  ],
  "steps": {
   "en": [
    {
     "title": "Choose a home miner",
     "text": "Browse the Home Mining collection on powermining.io (for example Bitaxe or NerdQaxe devices) and add a device to your cart."
    },
    {
     "title": "Pay at checkout",
     "text": "PowerMining accepts credit cards, PayPal and Bitcoin via BTCPay. Businesses can request an invoice by providing a VAT number and company details."
    },
    {
     "title": "Receive delivery",
     "text": "The order ships to your address. Report damaged items to support with photos; address changes are possible before shipment."
    },
    {
     "title": "Connect device to WiFi",
     "text": "Connect the miner to a 2.4 GHz network (not 5 GHz) and disable VPNs. The FAQ suggests reflashing via the webflasher if connection fails."
    },
    {
     "title": "Set pool and payout address",
     "text": "Join a pool such as Braiins Pool for regular payouts, or solo mine by entering your own BTC address, e.g. on pool.powermining.io."
    }
   ]
  }
 },
 "bitgo": {
  "name": "BitGo",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://www.bitgo.com/products/qualified-custody/",
   "https://www.bitgo.com/resource-center/account-setup/",
   "https://www.bitgo.com/resource-center/getting-started/",
   "https://www.bitgo.com/resource-center/understanding-bitgo-wallets/",
   "https://www.bitgo.com/resource-center/video-id-verification/"
  ],
  "open_questions": [
   "KYB document list for direct institutional custody clients not published on pages read.",
   "Which BitGo entity serves EU clients and how funding works not confirmed."
  ],
  "steps": {
   "en": [
    {
     "title": "Contact BitGo sales",
     "text": "Use the 'Connect With Us' form on bitgo.com. During the sales process the primary account holder is identified as Organization Owner."
    },
    {
     "title": "Activate the organization account",
     "text": "After the sales process the Org Owner receives an email, clicks 'Get Started', sets a password, verifies the account by email and logs in."
    },
    {
     "title": "Set up authentication",
     "text": "In app.bitgo.com Account Settings, add a passkey, hardware security key or 2FA authenticator app. The BitGo Verify mobile app uses these methods."
    },
    {
     "title": "Create custody wallets",
     "text": "Custody wallets are BitGo-managed cold wallets where BitGo holds all three keys; high-security withdrawals often include a video ID call with a BitGo operator."
    }
   ]
  }
 },
 "sygnum": {
  "name": "Sygnum",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://www.sygnum.com/help/onboarding/",
   "https://www.sygnum.com/help/",
   "https://start.join.sygnum.com/"
  ],
  "open_questions": [
   "Sygnum does not onboard retail clients or US persons; private qualified investors CHF 50,000 per FAQ; corporate fees not checked.",
   "start.join.sygnum.com form steps not read."
  ],
  "steps": {
   "en": [
    {
     "title": "Start the client application",
     "text": "Use the 'Become a client' page (start.join.sygnum.com) or the contact form. Sygnum serves professional and institutional investors, corporates and financial institutions."
    },
    {
     "title": "Discuss required documents",
     "text": "Required documents depend on client category and onboarding method; Sygnum asks you to discuss documentation with its onboarding team."
    },
    {
     "title": "Complete onboarding review",
     "text": "Sygnum states institutional accounts typically open within four to six weeks after all documentation is complete; complex cases may take longer."
    },
    {
     "title": "Log in to e-banking",
     "text": "Access the Sygnum e-banking platform with your Contract ID and two-factor approval on your mobile device; a Relationship Manager is your contact."
    },
    {
     "title": "Deposit and withdraw digital assets",
     "text": "Deposit supported crypto assets to your Sygnum wallet. First withdrawals to your own external wallet are verified by Sygnum's screening tool in the Client Portal."
    }
   ]
  }
 },
 "coinbase-institutional": {
  "name": "Coinbase Institutional",
  "approved": false,
  "as_of": "2026-10-07",
  "sources": [
   "https://www.coinbase.com/prime",
   "https://help.coinbase.com/en/institutional-onboarding/documents/llc",
   "https://help.coinbase.com/en/institutional-onboarding/post-application/status",
   "https://help.coinbase.com/en/institutional-onboarding/prime/access-account"
  ],
  "open_questions": [
   "Funding/deposit steps after activation not read.",
   "Which Coinbase contracting entity applies to EU clients not confirmed.",
   "Document list differs by entity type; only the LLC/Ltd page was read in full."
  ],
  "steps": {
   "en": [
    {
     "title": "Start the business application",
     "text": "Click 'Get started' on coinbase.com/prime, which opens the institutional application at accounts.coinbase.com/businesssignup."
    },
    {
     "title": "Provide company documents",
     "text": "For an LLC/Ltd: articles of incorporation, shareholder register, directors register, source of funds dated within 3 months, and ID of authorized applicant and owners."
    },
    {
     "title": "Wait for onboarding review",
     "text": "Track status in the Applications tab: In Progress, Submitted, In Review, Approved. The team may request additional information."
    },
    {
     "title": "Activate your Prime account",
     "text": "Create a password via the activation email, sign in at prime.coinbase.com, verify your phone by SMS, then switch 2-step verification to a security key."
    }
   ]
  }
 }
};
