#!/usr/bin/env python3
"""Old Virtuse Exchange pages on blog.virtuse.com: rules from the CSV, and a live check.

Source of truth: partnerships/legacy-wp-redirects.csv (one row per WordPress page,
EN and /sk/): action 301 / 410 / keep, target, status ready / ras. Rows with status
`ras` wait for Ras's decision; flip them to `ready` in the CSV (or change the action)
and run `build` again.

    python3 seo-ops/legacy_redirects.py build   # writes the three rule files below
    python3 seo-ops/legacy_redirects.py check   # live check of every row (read-only)
    python3 seo-ops/legacy_redirects.py check --status ready
    python3 seo-ops/legacy_redirects.py merge-virtuse <server .htaccess> <out>

build writes into partnerships/:
  legacy-wp-redirection-import.csv      ready rows, for WordPress → Tools → Redirection → Import
  legacy-wp-redirection-import-ras.csv  rows waiting for Ras, same format (import after the OK)
  legacy-wp-htaccess.txt                the same rules as an .htaccess block (Apache/LiteSpeed);
                                        rows waiting for Ras are in it commented out
Use one of the two (Redirection plugin or .htaccess), not both.

check requests every path from three entry points (https://www.virtuse.com,
https://virtuse.com, https://blog.virtuse.com), follows redirects by hand and
reports: final code, final URL, number of hops. Expected: 410 rows end in 410,
301 rows end with 200 on the target, keep rows end in 200 on blog.virtuse.com.
From www.virtuse.com at most 2 hops (plan "SEO, staré URL…", step 1). Before the
rules are live every 301/410 row fails; that is the baseline.
"""
import csv, os, re, sys, urllib.request, urllib.parse, concurrent.futures as cf

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'partnerships/legacy-wp-redirects.csv')
OUT = os.path.join(ROOT, 'partnerships')
ENTRIES = ['https://www.virtuse.com', 'https://virtuse.com', 'https://blog.virtuse.com']
UA = {'User-Agent': 'Mozilla/5.0 virtuse-legacy-check'}

def rows(status=None):
    rs = list(csv.DictReader(open(SRC, encoding='utf-8')))
    for r in rs:
        assert r['action'] in ('301', '410', 'keep'), r
        assert r['status'] in ('ready', 'ras'), r
        assert (r['action'] == '301') == bool(r['target']), r
    return [r for r in rs if not status or r['status'] == status]

def build():
    rs = [r for r in rows() if r['action'] != 'keep']
    for status, name in (('ready', 'legacy-wp-redirection-import.csv'), ('ras', 'legacy-wp-redirection-import-ras.csv')):
        with open(os.path.join(OUT, name), 'w', newline='', encoding='utf-8') as f:
            w = csv.writer(f)
            w.writerow(['source', 'target', 'regex', 'code'])  # Redirection's CSV import columns
            for r in rs:
                if r['status'] == status:
                    w.writerow([r['path'], r['target'], '0', r['action']])
    lines = [
        '# Old Virtuse Exchange pages → 301 to the new page or 410 Gone.',
        '# Generated by seo-ops/legacy_redirects.py from partnerships/legacy-wp-redirects.csv; edit the CSV, not this.',
        '# blog.virtuse.com: put this block ABOVE "# BEGIN WordPress" in the WordPress .htaccess.',
        '# virtuse.com (optional, saves one hop): put it ABOVE the rule that sends unknown paths to blog.virtuse.com.',
        '# Lines starting with "#   RewriteRule" wait for Ras (status "ras" in the CSV).',
        '<IfModule mod_rewrite.c>',
        'RewriteEngine On',
    ]
    for r in rs:
        pat = '^' + r['path'].strip('/').replace('.', r'\.') + '/?$'
        rule = f'RewriteRule {pat} - [G,L]' if r['action'] == '410' else f'RewriteRule {pat} {r["target"]} [R=301,L]'
        lines.append(rule if r['status'] == 'ready' else '#   ' + rule)
    lines += ['</IfModule>', '']
    open(os.path.join(OUT, 'legacy-wp-htaccess.txt'), 'w', encoding='utf-8').write('\n'.join(lines))
    n_ready = sum(r['status'] == 'ready' for r in rs)
    print(f'{len(rs)} rules: {n_ready} ready, {len(rs) - n_ready} waiting for Ras → partnerships/legacy-wp-*')

CATCH_ALL = 'RewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^(.*)$ https://blog.virtuse.com/$1 [R=301,L]'
BEGIN, END = '# BEGIN legacy-exchange (seo-ops/legacy_redirects.py)', '# END legacy-exchange'

def merge_virtuse(src, out):
    """virtuse.com's public_html/.htaccess (server only, not in the repo) with the legacy block
    inserted right before its catch-all to the blog, so www.virtuse.com/<old path> is 2 hops
    (www → apex → target) and 410s are answered on virtuse.com itself. Re-running replaces
    the block between the BEGIN/END markers."""
    s = open(src, encoding='utf-8').read()
    s = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n\n?', '', s, flags=re.S)
    if s.count(CATCH_ALL) != 1: sys.exit('catch-all rule to blog.virtuse.com not found exactly once')
    rules = [l for l in open(os.path.join(OUT, 'legacy-wp-htaccess.txt'), encoding='utf-8').read().splitlines()
             if l.startswith('RewriteRule ') or l.startswith('#   RewriteRule ')]
    block = '\n'.join([BEGIN, '# Old Virtuse Exchange paths: 301 to the new page or 410 Gone, before the blog fallback.',
                       '# Source: partnerships/legacy-wp-redirects.csv. Commented lines wait for Ras.'] + rules + [END, '', ''])
    s = s.replace(CATCH_ALL, block + CATCH_ALL, 1)
    open(out, 'w', encoding='utf-8').write(s)
    print(f'{out}: {sum(1 for r in rules if r.startswith("RewriteRule"))} active rules before the blog fallback')

class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *a, **k): return None
OPENER = urllib.request.build_opener(NoRedirect)

def chain(url, limit=8):
    hops = []
    for _ in range(limit):
        try:
            resp = OPENER.open(urllib.request.Request(url, headers=UA, method='GET'), timeout=90)
            return hops, resp.status, url
        except urllib.error.HTTPError as e:
            if e.code in (301, 302, 303, 307, 308) and e.headers.get('Location'):
                hops.append((e.code, url))
                url = urllib.parse.urljoin(url, e.headers['Location'])
                continue
            return hops, e.code, url
        except Exception as e:
            return hops, 'ERR ' + str(e)[:60], url
    return hops, 'LOOP', url

def norm(u): return u.rstrip('/') if not u.endswith('.html') else u

def check_row(r):
    out = []
    for entry in ENTRIES:
        hops, code, final = chain(entry + r['path'])
        if r['action'] == '410':
            ok = code == 410
        elif r['action'] == '301':
            ok = code == 200 and norm(final) == norm(r['target'])
        else:
            ok = code == 200 and final.startswith('https://blog.virtuse.com/')
        if entry == 'https://www.virtuse.com' and len(hops) > 2 and r['action'] != 'keep':
            ok = ok and 'hops'
        out.append((entry, ok, code, final, len(hops)))
    return r, out

def check(status):
    rs = rows(status)
    with cf.ThreadPoolExecutor(6) as ex:
        res = list(ex.map(check_row, rs))
    bad = 0
    for r, out in res:
        fails = [o for o in out if o[1] is not True]
        if fails:
            bad += 1
            print(f"FAIL {r['path']}  expect {r['action']} {r['target']}".rstrip())
            for entry, ok, code, final, n in fails:
                why = 'more than 2 hops from www' if ok == 'hops' else f'got {code} at {final}'
                print(f"     from {entry}: {why} ({n} hops)")
    print(f'{len(rs) - bad}/{len(rs)} rows OK' + (f' (status={status})' if status else ''))
    return bad

if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else ''
    if cmd == 'build': build()
    elif cmd == 'merge-virtuse': merge_virtuse(sys.argv[2], sys.argv[3])
    elif cmd == 'check':
        st = sys.argv[sys.argv.index('--status') + 1] if '--status' in sys.argv else None
        sys.exit(1 if check(st) else 0)
    else: sys.exit(__doc__)
